#!/usr/bin/env sh
# Generated by SMADP MCP Adapter Scaffolder. Receives the agent task via the
# SMADP_AGENT_TASK env var, writes it to /work/task.txt, then invokes the
# agent's binary.
set -eu

mkdir -p /work
if [ -n "${SMADP_AGENT_TASK:-}" ]; then
  printf '%s\n' "$SMADP_AGENT_TASK" > /work/task.txt
fi

exec python -m build26_lab520_get_started_with_models_in_microsoft_foundry_to_b
