# Generated by SMADP MCP Adapter Scaffolder.
FROM golang:1.21-alpine

ARG REPO_URL={{repo_url}}
ARG COMMIT_PIN={{commit_pin}}

RUN apk add --no-cache git

WORKDIR /app
RUN git clone "$REPO_URL" . && git checkout "$COMMIT_PIN"
RUN go build -o /usr/local/bin/agent ./...

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
