# Generated by SMADP MCP Adapter Scaffolder.
FROM node:20-alpine

ARG REPO_URL={{repo_url}}
ARG COMMIT_PIN={{commit_pin}}

RUN apk add --no-cache git

WORKDIR /app
RUN git clone "$REPO_URL" . && git checkout "$COMMIT_PIN"
RUN npm install --no-audit --no-fund

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
