"""Tests for MCPAdapterScaffolder."""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import MagicMock

from smadp.autopilot.scaffolders.language_detector import Language
from smadp.autopilot.scaffolders.mcp_adapter import (
    MCPAdapterScaffolder,
)

FIXTURES = Path(__file__).resolve().parent / "fixtures"


def _profile() -> dict:
    return json.loads((FIXTURES / "python_profile.json").read_text())


def _detector(language: Language = Language.PYTHON):
    det = MagicMock()
    det.detect = MagicMock(return_value=language)
    return det


def test_scaffold_writes_four_files(tmp_path: Path) -> None:
    sc = MCPAdapterScaffolder(detector=_detector(), commit_pin_resolver=lambda gh: "abc123")
    result = sc.scaffold(_profile(), target_dir=tmp_path / "gpt-researcher")
    assert result.success
    files = {p.name for p in result.files_written}
    assert files == {"Dockerfile", "entrypoint.sh", "mcp.json", ".scaffolded.json"}


def test_scaffold_fails_when_no_github_source(tmp_path: Path) -> None:
    profile = {"slug": "x", "name": "X", "evidence_level": "docs-only"}
    sc = MCPAdapterScaffolder(detector=_detector(), commit_pin_resolver=lambda gh: "abc")
    result = sc.scaffold(profile, target_dir=tmp_path / "x")
    assert not result.success
    assert result.reason == "no_github_source"


def test_scaffold_fails_when_unsupported_language(tmp_path: Path) -> None:
    sc = MCPAdapterScaffolder(
        detector=_detector(Language.UNSUPPORTED),
        commit_pin_resolver=lambda gh: "abc",
    )
    result = sc.scaffold(_profile(), target_dir=tmp_path / "x")
    assert not result.success
    assert result.reason == "unsupported_language"


def test_scaffold_fails_when_profile_not_enriched(tmp_path: Path) -> None:
    profile = _profile()
    profile["evidence_level"] = "unverified-profile"
    sc = MCPAdapterScaffolder(detector=_detector(), commit_pin_resolver=lambda gh: "abc")
    result = sc.scaffold(profile, target_dir=tmp_path / "x")
    assert not result.success
    assert result.reason == "profile_not_enriched"


def test_mcp_json_validates_against_existing_adapter_shape(tmp_path: Path) -> None:
    sc = MCPAdapterScaffolder(detector=_detector(), commit_pin_resolver=lambda gh: "abc123def")
    sc.scaffold(_profile(), target_dir=tmp_path / "gpt-researcher")
    mcp = json.loads((tmp_path / "gpt-researcher" / "mcp.json").read_text())
    for required in (
        "schema_version",
        "slug",
        "name",
        "repo_url",
        "command",
        "env_required",
        "image",
        "capabilities",
        "io_surfaces",
        "trust_floor",
        "docker_args",
    ):
        assert required in mcp, f"missing required key: {required}"
    assert mcp["scaffolded"] is True
    assert mcp["capabilities"]["network_egress"] == "broad"
    assert mcp["docker_args"]["network"] == "host"
    assert "OPENAI_API_KEY" in mcp["env_required"]


def test_dockerfile_pins_repo_url_and_commit(tmp_path: Path) -> None:
    sc = MCPAdapterScaffolder(detector=_detector(), commit_pin_resolver=lambda gh: "abc123")
    sc.scaffold(_profile(), target_dir=tmp_path / "gpt-researcher")
    dockerfile = (tmp_path / "gpt-researcher" / "Dockerfile").read_text()
    assert "https://github.com/assafelovic/gpt-researcher" in dockerfile
    assert "abc123" in dockerfile
    assert dockerfile.startswith("# Generated by SMADP")


def test_provenance_metadata_written(tmp_path: Path) -> None:
    sc = MCPAdapterScaffolder(detector=_detector(), commit_pin_resolver=lambda gh: "abc")
    sc.scaffold(_profile(), target_dir=tmp_path / "gpt-researcher")
    prov = json.loads((tmp_path / "gpt-researcher" / ".scaffolded.json").read_text())
    assert prov["slug"] == "gpt-researcher"
    assert prov["language"] == "python"
    assert prov["commit_pin"] == "abc"
    assert "scaffolded_at" in prov


def test_scaffolded_mcp_json_matches_existing_aider_schema(tmp_path: Path) -> None:
    """Spot-check: scaffold output is a superset of existing aider keys."""
    sc = MCPAdapterScaffolder(detector=_detector(), commit_pin_resolver=lambda gh: "abc")
    sc.scaffold(_profile(), target_dir=tmp_path / "gpt-researcher")
    generated = json.loads((tmp_path / "gpt-researcher" / "mcp.json").read_text())
    required_keys = {
        "schema_version",
        "slug",
        "name",
        "description",
        "homepage",
        "repo_url",
        "transport",
        "command",
        "env_required",
        "env_optional",
        "image",
        "capabilities",
        "io_surfaces",
        "trust_floor",
    }
    missing = required_keys - generated.keys()
    assert not missing, f"missing keys: {missing}"
    assert "scaffolded" in generated
    assert "docker_args" in generated
